name: Develop Check
on:
  push:

jobs:
  lint-check:
    name: Lint
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: ESLint & Prettier
        run: yarn lint-check
